version: '3'

services:
  dns:
    container_name: dns
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000"
    networks:
      - lab5_network
    restart: unless-stopped
    volumes:
      - volume_dns_work:/opt/adguardhome/work
      - volume_dns_conf:/opt/adguardhome/conf
    hostname: dns
    cap_add:
      - NET_ADMIN
# Добавьте ограничения на CPU и RAM по необходимости
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  registry:
    container_name: registry
    hostname: registry
    image: registry:2
    networks:
      - lab5_network
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - dns
# Добавьте ограничения на CPU и RAM по необходимости
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    volumes:
      - ./auth:/auth

  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lab5_network
    volumes:
      - ./nginx/conf/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/ssl
      #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      #- ./auth/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
    restart: unless-stopped
    depends_on:
      - dns
      - registry
    hostname: web
# Добавьте ограничения на CPU и RAM по необходимости
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  lab5_network:

volumes:
  volume_dns_work:
  volume_dns_conf:
