
#ENV["VAGRANT_EXPERIMENTAL"] = "disks"

$script1 = <<END
apt-get update
apt install nginx
systemctl start nginx
END

$script2 = <<END
apt-get update
apt-get update
apt-get install ca-certificates curl gnupg
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
END

$script3 = <<END
apt-get update
apt install zsh
useradd -d /home/adam -s /bin/zsh adam
echo 'adam ALL=(ALL) NOPASSWD:ALL' | tee -a /etc/sudoers
END

Vagrant.configure("2") do |config|
  #export VAGRANT_EXPERIMENTAL="disks"
  config.vm.box = "ubuntu/jammy64"
  # config.vm.disk :disk, size: "60GB", primary: true
  # config.vm.disk :disk, size: "10GB", name: "extra_storage"
  #config.disksize.size = '60GB'
  #config.disksize.size = '63GB'

  config.vm.define "vm1" do |vm1|
    vm1.name = "vm1"
    vm1.vm.box = "ubuntu/jammy64"
    vm1.vm.provider :virtualbox
    vm1.vm.network "forwarded_port", guest: 80, host: 8080
    vm1.vm.provision "shell", inline: $script1
    vm1.vm.network "private_network", ip: "172.20.1.1"
  end

  config.vm.define "vm2" do |vm2|
    vm2.name = "vm2"
    vm2.vm.box = "ubuntu/jammy64"
    vm2.vm.provider :virtualbox
    vm2.vm.disk :disk, size: "60GB", primary: true
    vm2.vm.network "public_network"
    vm2.vm.provision "shell", inline: $script2
  end

  config.vm.define "vm3" do |vm3|
    vm3.name = "vm3"
    vm3.vm.box = "ubuntu/jammy64"
    vm3.vm.provider :virtualbox
    vm3.vm.network "private_network", ip: "172.20.3.3"
    vm3.vm.provision "shell", inline: $script3
  end
end
